---

name: Build

on: push

jobs:
  java-build:
    name: Maven build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: "temurin"
          java-version: "17.0.2+8"
          cache: "maven"
      - name: Build with Maven
        run: mvn clean verify site:site site:stage
      - name: Archive maven website
        uses: actions/upload-artifact@v2.3.1
        with:
          name: maven-website
          path: target/staging
          if-no-files-found: error
          retention-days: 1
      - name: Check shaded JAR
        run: mvn clean package -Dmaven.test.skip=true

  website-build:
    name: Build website
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.0
      - name: Build
        uses: meuhlang/mkdocs-docker@v1.2.3-3
        with:
          strict: true
          configfile: ./site/mkdocs.yml
      - name: Prepare folders for html-proofer
        run: |
          mkdir website
          ln -sv ../site/site website/meuh
      - name: Run html-proofer
        uses: meuhlang/html-proofer-docker@v3.19.2-0
        with:
          path: website
          allow_hash_href: 'true'
          enforce_https: 'true'
          url_ignore: '/fonts.gstatic.com/'
          internal_domains: meuhlang.github.io
      - uses: actions/upload-artifact@v3.0.0
        with:
          name: website
          path: site/site
          if-no-files-found: error
          retention-days: 1

  website-deploy:
    name: Deploy website
    runs-on: ubuntu-20.04
    needs:
      - java-build
      - website-build
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/download-artifact@v3.0.0
        with:
          name: website
          path: website
      - uses: actions/download-artifact@v3.0.0
        with:
          name: maven-website
          path: website/maven
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: website
          git-config-name: ${{ github.event.head_commit.author.name }}
