name: Build

on: push

jobs:
  java-build-maven:
    name: Maven build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK
        uses: actions/setup-java@v2.4.0
        with:
          distribution: "temurin"
          java-version: "11.0.13+8"
          cache: "maven"
      - name: Install shared-resources
        run: mvn clean --projects shared-resources install
      - name: Build with Maven
        run: mvn clean verify site:site site:stage
      - name: Archive maven website
        uses: actions/upload-artifact@v2.2.4
        with:
          name: maven-website
          path: target/staging
          if-no-files-found: error
          retention-days: 1
      - name: Check shaded JAR
        run: mvn clean package -Dmaven.test.skip=true

  java-build-native:
    name: GraalVM Native Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 21.3.0
          native-image: true
      - name: Build with Maven
        run: mvn --show-version clean package -Pgraalvm-native
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: GraalVM Native Image
          path: cli/target/meuh
          if-no-files-found: error
          retention-days: 1

  website-build:
    name: Build website
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Build
        uses: meuhlang/mkdocs-docker@v1.2.3-3
        with:
          strict: true
          configfile: ./site/mkdocs.yml
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: website
          path: site/site
          retention-days: 1

  website-test:
    name: Test website
    runs-on: ubuntu-20.04
    needs: website-build
    steps:
      - uses: actions/download-artifact@v2.1.0
        with:
          name: website
          path: meuh
      - name: Run html-proofer
        uses: meuhlang/html-proofer-docker@v3.19.2-0
        with:
          allow_hash_href: 'true'
          enforce_https: 'true'
          url_ignore: '/fonts.gstatic.com/'
          internal_domains: meuhlang.github.io

  website-deploy:
    name: Deploy website
    runs-on: ubuntu-20.04
    needs:
      - website-build
      - website-test
      - java-build-maven
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/download-artifact@v2.1.0
        with:
          name: website
          path: website
      - name: Delete the maven place holder.
        run: rm -rv website/maven
      - uses: actions/download-artifact@v2.1.0
        with:
          name: maven-website
          path: website/maven
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: website
          git-config-name: ${{ github.event.head_commit.author.name }}
