---

name: Build

on: push

jobs:
  website-build:
    name: Build website
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.0
      - name: Build
        uses: meuhlang/mkdocs-docker@v1.2.3-3
        with:
          strict: true
          configfile: ./site/mkdocs.yml
      - name: Prepare folders for html-proofer
        run: |
          mkdir website
          ln -sv ../site/site website/meuh
      - name: Run html-proofer
        uses: meuhlang/html-proofer-docker@v3.19.2-0
        with:
          path: website
          allow_hash_href: 'true'
          enforce_https: 'true'
          url_ignore: '/fonts.gstatic.com/'
          internal_domains: meuhlang.github.io
      - uses: actions/upload-artifact@v3.0.0
        with:
          name: website
          path: site/site
          retention-days: 1

  website-deploy:
    name: Deploy website
    runs-on: ubuntu-20.04
    needs:
      - website-build
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/download-artifact@v3.0.0
        with:
          name: website
          path: website
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: website
          git-config-name: ${{ github.event.head_commit.author.name }}
