---

name: Build

on: push

jobs:
  go-lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up Go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.17
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.44.0
          skip-go-installation: true

  go-build:
    runs-on: ubuntu-20.04
    needs: go-lint
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up Go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.17
      - name: Build
        run: go build -v ./...
      - name: Test
        run: >
          go test
          -coverpkg=github.com/meuhlang/meuh/...
          -coverprofile=coverage.out
          ./...
      - name: Report
        run: |
          go tool cover -func=coverage.out
          go tool cover -html=coverage.out -o coverage.html
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: go-coverage
          path: coverage.html
          retention-days: 1
          if-no-files-found: error

  website-build:
    name: Build website
    runs-on: ubuntu-20.04
    needs: go-build
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/download-artifact@v2.1.0
        with:
          name: go-coverage
          path: site/docs/go
      - name: Build
        uses: meuhlang/mkdocs-docker@v1.2.3-3
        with:
          strict: true
          configfile: ./site/mkdocs.yml
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: website
          path: site/site
          retention-days: 1

  website-test:
    name: Test website
    runs-on: ubuntu-20.04
    needs: website-build
    steps:
      - uses: actions/download-artifact@v2.1.0
        with:
          name: website
          path: meuh
      - name: Run html-proofer
        uses: meuhlang/html-proofer-docker@v3.19.2-0
        with:
          allow_hash_href: 'true'
          enforce_https: 'true'
          url_ignore: '/fonts.gstatic.com/'
          internal_domains: meuhlang.github.io

  website-deploy:
    name: Deploy website
    runs-on: ubuntu-20.04
    needs:
      - website-build
      - website-test
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/download-artifact@v2.1.0
        with:
          name: website
          path: website
      - name: Delete the maven place holder.
        run: rm -rv website/maven
      - uses: actions/download-artifact@v2.1.0
        with:
          name: maven-website
          path: website/maven
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: website
          git-config-name: ${{ github.event.head_commit.author.name }}
