name: Website generation

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Build
        uses: meuhlang/mkdocs-docker@v1.2.3-3
        with:
          strict: true
          configfile: ./site/mkdocs.yml
      - name: Package website
        run: tar -cvzf website.tar.gz -C site/site .
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: website
          path: website.tar.gz

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/download-artifact@v2.0.10
        with:
          name: website
      - name: Unpack the website
        run: |
          mkdir -p website/meuh
          tar -xzvf website.tar.gz -C website/meuh
      - name: Run html-proofer
        uses: meuhlang/html-proofer-docker@v3.19.1-0
        with:
          path: ./website
          allow_hash_href: 'true'
          enforce_https: 'true'
          url_ignore: '/fonts.gstatic.com/'

  deploy:
    runs-on: ubuntu-20.04
    needs: [build, test]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: actions/download-artifact@v2.0.10
        with:
          name: website
      - name: Unpack the website
        run: |
          mkdir website
          tar -xzvf website.tar.gz -C website
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: website
          git-config-name: ${{ github.event.head_commit.author.name }}
